* Add caching and improve configure system (ported from rspamd) * Fix error when tempdir is not properly set on reload (reported by: ozz) * Fix some logic in creation of tempfile (reported by: ozz)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9,7 +9,6 @@ OS=""
 LOCALBASE=/usr/local
 PREFIX=$LOCALBASE
 
-VERSION=1.5.17
 DCC_VER=1.2.74
 COMPAT_DIR="./compat"
 
@@ -23,8 +22,8 @@ SOURCES="upstream.c regexp.c spf.c rmilter.c libclamc.c cfg_file.c ratelimit.c m
 CFLAGS="$CFLAGS -W -Wall -Wpointer-arith -Wno-unused-parameter"
 CFLAGS="$CFLAGS -Wno-unused-function -Wunused-variable -Wno-sign-compare"
 CFLAGS="$CFLAGS -Wunused-value -ggdb -I${LOCALBASE}/include"
-CFLAGS="$CFLAGS -DMVERSION=\\\"${VERSION}\\\" -DHASH_COMPAT"
-LDFLAGS="$LDFLAGS -L/usr/lib -L${LOCALBASE}/lib"
+CFLAGS="$CFLAGS -DHASH_COMPAT"
+LDFLAGS="$LDFLAGS -L${LOCALBASE}/lib"
 PTHREAD_CFLAGS="-D_THREAD_SAFE"
 OPT_FLAGS="-O -pipe -fno-omit-frame-pointer"
 DEPS="awl.h cfg_file.h libclamc.h libspamd.h memcached.h radix.h ratelimit.h regexp.h rmilter.h spf.h upstream.h ${LEX_OUTPUT} ${YACC_OUTPUT}"
@@ -35,24 +34,69 @@ SENDMAIL=no
 INSTALL="/usr/bin/install -v"
 MKDIR="/usr/bin/install -v -d"
 MANPATH="${PREFIX}/share/man"
+CACHE=config.cache
 
 MAKEFILE="Makefile"
 MAKEFILE_IN="Makefile.in"
 
 TARGETS="${EXEC}"
 
+check_cache()
+{
+	type=$1
+	name=$2
+	
+	if [ -f $CACHE ] ; then
+		line=`fgrep "$type:$name" $CACHE 2>/dev/null`
+		if [ $? -eq 0 ] ; then
+			result=`echo $line | cut -d ':' -f 3`
+			CACHED=`echo $line | cut -d ':' -f 4-`
+			if [ "F$result" = "Fyes" ] ; then
+				return 0
+			elif [ "F$result" = "Fno" ] ; then
+				return 1
+			else
+				return 2
+			fi
+		else
+			return 3
+		fi
+	else
+		return 3
+	fi
+}
+
+write_cache()
+{
+	type=$1
+	name=$2
+	result=$3
+	value=$4
+
+	echo "$type:$name:$result:$value" >> $CACHE
+}
+
 cleanup()
 {
 	rm -f autotest.c
 	rm -f autotest
+	INCLUDE=""
 }
 
 check_compiler()
 {	
-	GCC=`PATH="$PATH:$PREFIX/bin:$LOCALBASE/bin" which gcc`
 	echo -n "Testing for gcc: "
+	check_cache "compiler" "gcc"
+	if [ $? -eq 0 ] ; then
+		GCC=$CACHED
+		echo "found(cached) -> $GCC"
+		return 0
+	fi
+
+	GCC=`PATH="$PATH:$PREFIX/bin:$LOCALBASE/bin" which gcc`
 	if [ -x $GCC ] ; then
 		echo "found -> $GCC"
+		write_cache "compiler" "gcc" "yes" "$GCC"
 		return 0
 	else
 		echo "not found"
@@ -61,11 +105,18 @@ check_compiler()
 }
 
 check_make()
-{
-	MAKE=`PATH="$PATH:$PREFIX/bin:$LOCALBASE/bin" which make`
+{	
 	echo -n "Testing for make: "
+	check_cache "make" "make"
+	if [ $? -eq 0 ] ; then
+		MAKE=$CACHED
+		echo "found(cached) -> $MAKE"
+		return 0
+	fi
+	MAKE=`PATH="$PATH:$PREFIX/bin:$LOCALBASE/bin" which make`
 	if [ -x $MAKE ] ; then
 		echo "found -> $MAKE"
+		write_cache "make" "make" "yes" "$MAKE"
 		return 0
 	else
 		echo "not found"
@@ -76,10 +127,18 @@ check_make()
 
 check_lex()
 {
-	LEX=`PATH="$PATH:$PREFIX/bin:$LOCALBASE/bin" which lex`
 	echo -n "Testing for lex: "
+	check_cache "binary" "lex"
+	if [ $? -eq 0 ] ; then
+		LEX=$CACHED
+		echo "found(cached) -> $LEX"
+		return 0
+	fi
+
+	LEX=`PATH="$PATH:$PREFIX/bin:$LOCALBASE/bin" which lex`
 	if [ -x $LEX ] ; then
 		echo "found -> $LEX"
+		write_cache "binary" "lex" "yes" "$LEX"
 		return 0
 	else
 		echo "not found"
@@ -90,10 +149,19 @@ check_lex()
 
 check_yacc()
 {
+	echo -n "Testing for yacc: "
+	check_cache "binary" "yacc"
+	if [ $? -eq 0 ] ; then
+		YACC=$CACHED
+		echo "found(cached) -> $YACC"
+		return 0
+	fi
+
 	YACC=`PATH="$PATH:$PREFIX/bin:$LOCALBASE/bin" which yacc`
 	echo -n "Testing for yacc: "
 	if [ -x $YACC ] ; then
 		echo "found -> $YACC"
+		write_cache "binary" "yacc" "yes" "$YACC"
 		return 0
 	else
 		echo "not found"
@@ -102,15 +170,51 @@ check_yacc()
 
 }
 
+check_util()
+{
+	echo -n "Testing for $1: "
+	check_cache "binary" "$1"
+	if [ $? -eq 0 ] ; then
+		echo "found(cached) -> $CACHED"
+		return 0
+	fi
+	UTIL=`PATH="$PATH:$PREFIX/bin:$LOCALBASE/bin" which $1`
+	if [ -x $UTIL ] ; then
+		echo "found -> $UTIL"
+		write_cache "binary" "$1" "yes" "$UTIL"
+		return 0
+	else
+		echo "not found"
+		exit 1
+	fi
+
+}
 
 check_function()
 {
 	FUNCTION=$1
-	INCLUDE=$2
+	while [ $# -ne 0 -a -n $2 ] ; do 
+		shift
+		if [ "F$INCLUDE" = "F" ] ; then
+			INCLUDE="$1"
+		else
+			INCLUDE="$INCLUDE $1"
+		fi
+	done
 	echo -n "Testing for $FUNCTION: "
+	echo >> config.log
+	echo "Testing for $FUNCTION: " >> config.log
+	check_cache "function" "$FUNCTION"
+	if [ $? -eq 0 ] ; then
+		echo "-> OK (cached)"
+		echo "-> OK (cached)" >> config.log
+		return 0
+	fi
 	echo "#include <sys/types.h>" > autotest.c
 	if [ "F$INCLUDE" != "F" ] ; then
-		echo "#include <$INCLUDE>" >> autotest.c
+		for inc in $INCLUDE ; do
+			echo "#include \"$inc\"" >> autotest.c
+		done
 	fi
 	echo "#include <stdlib.h>" >> autotest.c
 	echo "int main (int argc, char **argv) { $FUNCTION; return 0; }" >> autotest.c
@@ -120,36 +224,53 @@ check_function()
 		echo "found"
 		cleanup
 		echo "-> OK" >> config.log
+		write_cache "function" "$FUNCTION" "yes" ""
 		return 0
 	else
 		echo "not found"
-		cleanup
 		echo "-> FAILED" >> config.log
+		echo "Failed program was:" >> config.log
+		cat autotest.c >> config.log
+		cleanup
+		write_cache "function" "$FUNCTION" "no" ""
 		return 1
 	fi
 }
 
 check_include()
 {
-	INCLUDE=$1
-	echo -n "Testing for $INCLUDE: "
+	_INCLUDE="$1"
+	echo -n "Testing for $_INCLUDE: "
+	echo >> config.log
+	echo "Testing for $_INCLUDE: " >> config.log
+	check_cache "include" "$_INCLUDE"
+	if [ $? -eq 0 ] ; then
+		echo "-> OK (cached)"
+		echo "-> OK (cached)" >> config.log
+		CFLAGS="$CFLAGS -DHAVE_$_CFLAG"
+		return 0
+	fi
 	echo "#include <sys/types.h>" > autotest.c
-	echo "#include <$INCLUDE>" >> autotest.c
+	echo "#include \"$_INCLUDE\"" >> autotest.c
 	echo "#include <stdlib.h>" >> autotest.c
 	echo "int main (int argc, char **argv) { return 0; }" >> autotest.c
 	echo "$GCC $CFLAGS $PTHREAD_CFLAGS -o autotest $LDFLAGS $LIBS $PTHREAD_LDFLAGS autotest.c" >>config.log
 	$GCC $CFLAGS $PTHREAD_CFLAGS -o autotest $LDFLAGS $LIBS $PTHREAD_LDFLAGS autotest.c >>config.log 2>&1
 	if [ $? -eq 0 ] ; then 
 		echo "found"
-		cleanup
 		echo "-> OK" >> config.log
-		_CFLAG=`echo "-DHAVE_$INCLUDE" | sed -e 's/[./]/_/g' | tr '[:lower:]' '[:upper:]'`
-		CFLAGS="$CFLAGS $_CFLAG"
+		_CFLAG=`echo "$_INCLUDE" | sed -e 's/[./]/_/g' | tr '[:lower:]' '[:upper:]'`
+		CFLAGS="$CFLAGS -DHAVE_$_CFLAG"
+		write_cache "include" "$_INCLUDE" "yes" "$_CFLAG"
+		cleanup
 		return 0
 	else
 		echo "not found"
-		cleanup
 		echo "-> FAILED" >> config.log
+		echo "Failed program was:" >> config.log
+		cat autotest.c >> config.log
+		write_cache "include" "$_INCLUDE" "no" ""
+		cleanup
 		return 1
 	fi
 }
@@ -157,27 +278,49 @@ check_include()
 check_macro()
 {
 	MACRO=$1
-	INCLUDE=$2
+	_INCLUDE=""
+	while [ $# -ne 1 -a -n $1 ] ; do 
+		shift
+		if [ "F$_INCLUDE" = "F" ] ; then
+			_INCLUDE="$1"
+		else
+			_INCLUDE="$_INCLUDE $1"
+		fi
+	done
 	echo -n "Testing for $MACRO: "
+	echo >> config.log
+	echo "Testing for $MACRO: " >> config.log
+	check_cache "macro" "$MACRO"
+	if [ $? -eq 0 ] ; then
+		echo "-> OK (cached)"
+		echo "-> OK (cached)" >> config.log
+		return 0
+	fi
 	echo "#include <sys/types.h>" > autotest.c
-	echo "#include \"${INCLUDE}\"" >> autotest.c
+	for _inc in $_INCLUDE ; do
+		echo "#include \"$_inc\"" >> autotest.c
+	done
 	echo "#include <stdlib.h>" >> autotest.c
 	echo "int main (int argc, char **argv) {" >>autotest.c
 	echo "#ifndef $MACRO" >>autotest.c
 	echo "#error \"$MACRO not defined\"" >>autotest.c 
 	echo "#endif" >> autotest.c
 	echo "}" >>autotest.c
-	echo "$GCC $CFLAGS $PTHREAD_CFLAGS -o autotest $LDFLAGS $LIBS $PTHREAD_LDFLAGS autotest.c" >>config.log
+	echo "$GCC $CFLAGS $PTHREAD_CFLAGS -o autotest $LDFLAGS $LIBS $PTHREAD_LDFLAGS autotest.c" >> config.log
 	$GCC $CFLAGS $PTHREAD_CFLAGS -o autotest $LDFLAGS $LIBS $PTHREAD_LDFLAGS autotest.c >>config.log 2>&1
 	if [ $? -eq 0 ] ; then 
 		echo "found"
-		cleanup
 		echo "-> OK" >> config.log
+		write_cache "macro" "$MACRO" "yes" ""
+		cleanup
 		return 0
 	else
 		echo "not found"
-		cleanup
 		echo "-> FAILED" >> config.log
+		echo "Failed program was:" >> config.log
+		cat autotest.c >> config.log
+		write_cache "macro" "$MACRO" "no" ""
+		cleanup
 		return 1
 	fi
 }
@@ -186,10 +329,29 @@ check_macro()
 check_lib()
 {
 	LIB=$1
+	while [ $# -ne 1 -a -n $1 ] ; do 
+		shift
+		if [ "F$INCLUDE" = "F" ] ; then
+			INCLUDE="$1"
+		else
+			INCLUDE="$INCLUDE $1"
+		fi
+	done
 	echo -n "Testing for lib$LIB: "
+	echo >> config.log
+	echo "Testing for lib$LIB: " >> config.log
+	check_cache "lib" "$LIB"
+	if [ $? -eq 0 ] ; then
+		LIBS="$LIBS -l$LIB"
+		echo "-> OK (cached)"
+		echo "-> OK (cached)" >> config.log
+		return 0
+	fi
 	echo "#include <sys/types.h>" > autotest.c
 	if [ "F$INCLUDE" != "F" ] ; then
-		echo "#include <$INCLUDE>" >> autotest.c
+		for inc in $INCLUDE ; do
+			echo "#include \"$inc\"" >> autotest.c
+		done
 	fi
 	echo "#include <stdlib.h>" >> autotest.c
 	echo "int main (int argc, char **argv) { return 0; }" >> autotest.c
@@ -198,13 +360,17 @@ check_lib()
 	if [ $? -eq 0 ] ; then 
 		echo "found"
 		LIBS="$LIBS -l$LIB"
-		cleanup
 		echo "-> OK" >> config.log
+		write_cache "lib" "$LIB" "yes" ""
+		cleanup
 		return 0
 	else
 		echo "not found"
-		cleanup
 		echo "-> FAILED" >> config.log
+		echo "Failed program was:" >> config.log
+		cat autotest.c >> config.log
+		write_cache "lib" "$LIB" "no" ""
+		cleanup
 		return 1
 	fi
 }
@@ -288,8 +454,6 @@ LIBS=$LIBS
 SOURCES=$SOURCES
 # ${EXEC} objects 
 OBJECTS=$OBJECTS
-# Version of product
-VERION=$VERSION
 # Detected operation system
 OS=$OS
 # Version of dcc (if needed)
@@ -412,7 +576,7 @@ if [ $? -eq 1 ] ; then
 	echo "Libmilter not found, check config.log for details"
 	exit 1
 fi
-check_lib "spf2" "spf2/spf.h"
+check_lib "spf2" "netinet/in.h" "spf2/spf.h"
 if [ $? -eq 1 ] ; then
 	echo "Libspf2 not found, check config.log for details"
 	exit 1
@@ -451,6 +615,7 @@ check_include "stdint.h"
 if [ $? -eq 1 ] ; then
 	check_include "inttypes.h"
 fi
+check_include "stdbool.h"
 check_include "strlcpy.h"
 check_include "md5.h"
 check_include "sys/queue.h"
