* Add ability to disable SPF support

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -17,7 +17,7 @@ LEX_SRC="cfg_file.l"
 YACC_OUTPUT="cfg_yacc.c"
 LEX_OUTPUT="cfg_lex.c"
 
-SOURCES="upstream.c regexp.c spf.c rmilter.c libclamc.c cfg_file.c ratelimit.c memcached.c beanstalk.c main.c radix.c awl.c libspamd.c ${LEX_OUTPUT} ${YACC_OUTPUT}"
+SOURCES="upstream.c regexp.c rmilter.c libclamc.c cfg_file.c ratelimit.c memcached.c beanstalk.c main.c radix.c awl.c libspamd.c ${LEX_OUTPUT} ${YACC_OUTPUT}"
 
 CFLAGS="$CFLAGS -Wall -Wpointer-arith"
 CFLAGS="$CFLAGS -ggdb -I${LOCALBASE}/include"
@@ -530,6 +530,7 @@ do
 		--group*)						 GROUP=$value								;;
 		--enable-auth-strict)			 CFLAGS="$CFLAGS -DSTRICT_AUTH"             ;;
 		--enable-dcc)                    dcc=yes                    				;;
+		--disable-spf)                   spf=no                                     ;;
 		--enable-debug)					 CFLAGS="$CFLAGS -DWITH_DEBUG" OPT_FLAGS=""	;;
 		--enable-opt)                    OPT_FLAGS="-O3 -pipe"						;;
 		--enable-sendmail)               SENDMAIL=yes                               ;;
@@ -552,6 +553,7 @@ if [ "F$help" = "Fyes" ] ; then
   --enable-opt                       turn on extra optimization
   --enable-auth-strict               turn on strict check for authenticated users
   --enable-sendmail                  build rmilter for using with sendmail MTA
+  --disable-spf                      disable spf support
   --user=USER                        set user to use
   --group=GROUP                      set group to use
 END
@@ -583,10 +585,16 @@ if [ $? -eq 1 ] ; then
 	echo "Libmilter not found, check config.log for details"
 	exit 1
 fi
-check_lib "spf2" "netinet/in.h" "spf2/spf.h"
-if [ $? -eq 1 ] ; then
-	echo "Libspf2 not found, check config.log for details"
-	exit 1
+
+if [ "F$spf" = "Fno" ] ; then
+	CFLAGS="$CFLAGS -DDISABLE_SPF"
+else
+	SOURCES="$SOURCES spf.c"
+	check_lib "spf2" "netinet/in.h" "spf2/spf.h"
+	if [ $? -eq 1 ] ; then
+		echo "Libspf2 not found, check config.log for details"
+		exit 1
+	fi
 fi
 
 check_lib "m"
